# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: sls-test1
provider:
  name: aws
  region: ap-northeast-1
functions:
  # sls-test1-dev-hello という関数名になる
  hello:
    handler: hello/index.handler
    runtime: nodejs8.10
  hello2:
    handler: hello2/index.handler
    description: あいうえお
    runtime: nodejs8.10
    memorySize: 512
    timeout: 10
    environment: # 環境変数
      HOGE: 12345678
